# Generated by Django 2.2.2 on 2019-06-06 11:46

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'a4_candy_projects'
         WHERE app_label = 'a4-speakup_projects';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'a4-speakup_projects';
                 WHERE app_label = 'a4_candy_projects';"""

class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_projects', '0001_initial'),
    ]

    operations = [
    ]
