# Generated by Django 2.2.2 on 2019-06-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_projects', '0002_update_content_types'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moderatorinvite',
            table=None,
        ),
        migrations.AlterModelTable(
            name='participantinvite',
            table=None,
        ),
    ]
