language: python
dist: bionic
python:
- '3.6'
node_js:
- '8'
cache:
  pip: true
  npm: true
install:
- npm install
- npm run build
- pip install -r requirements/dev.txt
- pip install coveralls
script:
- python manage.py collectstatic > /dev/null
#- py.test --cov
- python manage.py makemigrations --dry-run --check --noinput
- isort --diff -rc -c a4-speakup apps tests
- flake8 a4-speakup apps tests --exclude migrations,settings
- npm run lint
- rm -rf static/
after_success:
- coveralls
