# Generated by Django 2.2.2 on 2019-06-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_ideas', '0002_update_content_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='idea',
            table=None,
        ),
    ]
