# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', models.ForeignKey(blank=True, help_text='Please add a link to the page that explains the privacy policy here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_page_privacy_policy', to='wagtailcore.Page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
                ('terms_of_use_page', models.ForeignKey(blank=True, help_text='Please add a link to the page that explains the terms of condition here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_page_terms_of_use_page', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
