# Generated by Django 2.2.2 on 2019-06-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_questions', '0004_rename_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
