# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4-speakup_likes', '0003_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='session',
            field=models.CharField(max_length=255),
        ),
    ]
