# Generated by Django 2.2.2 on 2019-06-06 11:46

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'a4_candy_users'
         WHERE app_label = 'a4-speakup_users';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'a4-speakup_users';
                 WHERE app_label = 'a4_candy_users';"""

class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_users', '0002_add_notification'),
    ]

    operations = [
    ]
