# Generated by Django 2.2.2 on 2019-06-06 11:45

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'a4_candy_organisations'
         WHERE app_label = 'a4-speakup_organisations';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'a4-speakup_organisations';
                 WHERE app_label = 'a4_candy_organisations';"""

class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_organisations', '0001_initial'),
    ]

    operations = [
    ]
