# Generated by Django 2.2.2 on 2019-06-06 11:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('a4_candy_organisations', '0002_update_content_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organisation',
            table=None,
        ),
    ]
